[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
	cache-control = '''
	max-age=604800,
	no-cache,
	no-store,
	must-revalidate'''

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

  [build]
  publish = "build"